words = [
    {Chinese: "贪心 ", Pinyin: "Tānxīn ", English: "(adj.) Greed; avarice; rapacity " },
    {Chinese: "俯卧撑 ", Pinyin: "Fǔwòchēng ", English: "(n.) Push ups" },
    {Chinese: "勉强 ", Pinyin: "Miǎnqiáng ", English: "(adj)reluctant; (v.) force; (adv.) reluctantly  " },
    {Chinese: "力量 ", Pinyin: "Lìliàng ", English: "(n.) physical strength; force; power " },
    {Chinese: "各位 ", Pinyin: "Gèwèi ", English: "(n.) Everybody; everyone (term of address)" },
    {Chinese: "立场 ", Pinyin: "Lìchǎng ", English: "(n.) position; stand; standpoint " },
    {Chinese: "下礼拜 ", Pinyin: "Xià lǐbài ", English: "(n.) next week (used in Taiwan) " },
    {Chinese: "魂魄 ", Pinyin: "Húnpò ", English: "(n.) soul  " },
    {Chinese: "多媒体 ", Pinyin: "Duōméitǐ ", English: "(n.) multimedia " },
    {Chinese: "起哄 ", Pinyin: "Qǐhòng ", English: "(v.) to heckle " },
    {Chinese: "残杀 ", Pinyin: "Cánshā ", English: "(v.) murder in cold blood; massacre " },
    {Chinese: "设计 ", Pinyin: "Shèjì ", English: "(v.) design; plan " },
    {Chinese: "蛋黄 ", Pinyin: "Dànhuáng ", English: "(n.) yolk " },
    {Chinese: "尖叫 ", Pinyin: "Jiānjiào ", English: "(v.) scream; shriek; yell " },
    {Chinese: "魔法师 ", Pinyin: "Mófǎshī ", English: "(n.) Magician; wizard; sorcerer" },
    {Chinese: "联络 ", Pinyin: "Liánluò ", English: "(n.) contact " },
    {Chinese: "留恋 ", Pinyin: "Liúliàn ", English: "(v.) be reluctant to leave (a place); cant bear to part (something or someone); recall with nostalgia  " },
    {Chinese: "喜剧 ", Pinyin: "Xǐjù ", English: "(n.) comedy " },
    {Chinese: "耐心 ", Pinyin: "Nàixīn ", English: "(n.) patience " },
    {Chinese: "固执 ", Pinyin: "Gùzhí ", English: "(adj.)obstinate; stubborn " },
    {Chinese: "订婚 ", Pinyin: "Dìnghūn ", English: "(v.) engaged to be married " },
    {Chinese: "家伙 ", Pinyin: "Jiāhuo ", English: "(n.) tool; weapon; guy; livestock " },
    {Chinese: "挑剔 ", Pinyin: "Tiāotì ", English: "(v.) nitpick; hypercritica" },
    {Chinese: "流利 ", Pinyin: "Liúlì ", English: "(adj) fluent; smooth " },
    {Chinese: "梅雨 ", Pinyin: "Méiyǔ ", English: "(n.) monsoon  " },
    {Chinese: "分店 ", Pinyin: "Fēndiàn ", English: "(n.) branch (of a shop) " },
    {Chinese: "动漫 ", Pinyin: "Dòngmàn ", English: "(n.) cartoon and animation" },
    {Chinese: "高级 ", Pinyin: "Gāojí ", English: "(adj.) senior; high-ranking  " },
    {Chinese: "稍微 ", Pinyin: "Shāowéi ", English: "(adv.) a little; a bit; slightly  " },
    {Chinese: "顺畅 ", Pinyin: "Shùnchàng ", English: "(adj.) smooth and easy; unhindered " },
    {Chinese: "来得及 ", Pinyin: "Láidéjí ", English: "(v.) there’s still time; be able to make it  " },
    {Chinese: "体内 ", Pinyin: "Tǐnèi ", English: "Within the body " },
    {Chinese: "意见 ", Pinyin: "Yìjiàn ", English: "(n.) idea; view; opinion; objection " },
    {Chinese: "一阵子 ", Pinyin: "Yī zhènzi ", English: "(n.) burst, fit; period (of time); spell " },
    {Chinese: "想得美 ", Pinyin: "Xiǎng dé měi ", English: "In your dreams! " },
    {Chinese: "吸引 ", Pinyin: "Xīyǐn ", English: "(v.) attract; draw; fascinate " },
    {Chinese: "记录 ", Pinyin: "Jìlù ", English: "(n.)  minutes; notes; record; notetaker " },
    {Chinese: "按键 ", Pinyin: "Ànjiàn ", English: "(n.) key; button " },
    {Chinese: "大一 ", Pinyin: "Dà yī ", English: "(n.) general idea; main points; gist" },
    {Chinese: "迎合 ", Pinyin: "Yínghé ", English: "(v.) cater to; pander to " },
    {Chinese: "破绽 ", Pinyin: "Pòzhàn ", English: "(n.) original meaning a burst seam; split also flaw; weak point " },
    {Chinese: "处死 ", Pinyin: "Chǔsǐ ", English: "(v.) execute; put to death " },
    {Chinese: "长知识 ", Pinyin: "Zhǎng zhīshì ", English: "(v.) to acquire knowledge " },
    {Chinese: "搭讪 ", Pinyin: "Dāshàn ", English: "(v.) strike up a conversation with somebody  " },
    {Chinese: "计划 ", Pinyin: "Jìhuà ", English: "(v.) plan (n.) plan " },
    {Chinese: "处置 ", Pinyin: "Chǔzhì ", English: "(v.) handle; deal with; manage; punish " },
    {Chinese: "庆祝 ", Pinyin: "Qìngzhù ", English: "(v.) celebrate " },
    {Chinese: "滴水 ", Pinyin: "Dīshuǐ ", English: "(v.) drip " },
    {Chinese: "推荐 ", Pinyin: "Tuījiàn ", English: "(v.) recommend " },
    {Chinese: "理性 ", Pinyin: "Lǐxìng ", English: "(n.) reason (adj.) rational  " },
    {Chinese: "砍 ", Pinyin: "Kǎn ", English: "(v.) cut; chop; hack; reduce " },
    {Chinese: "梨子 ", Pinyin: "Lízi ", English: "(n.) pear " },
    {Chinese: "某处 ", Pinyin: "Mǒu chù ", English: "(n.) somewhere " },
    {Chinese: "概念 ", Pinyin: "Gàiniàn ", English: "(n.) concept; conception; notion, idea, new design " },
    {Chinese: "探员 ", Pinyin: "Tàn yuán ", English: "(n.) detective " },
    {Chinese: "状态 ", Pinyin: "Zhuàngtài ", English: "(n.) state; condition; state of affairs " },
    {Chinese: "出现 ", Pinyin: "Chūxiàn ", English: "(v.) appear; arise; emerg" },
    {Chinese: "签约 ", Pinyin: "Qiānyuē ", English: "Sign an agreement or contract " },
    {Chinese: "辛苦 ", Pinyin: "Xīnkǔ ", English: "(v.) work hard (adj.) hard " },
    {Chinese: "统计学 ", Pinyin: "Tǒngjì xué", English: "(n.) statistics (the science) " },
    
]